# Site settings
title: Wandu Framework

email: im@wani.kr

permalink: /posts/:title/
paginate_path: /posts/page/:num

paginate: 10

# Build settings
highlighter: rouge
markdown: kramdown

sass:
    style: compressed
